### ISSUE TITLE
How does the SDK handle carts?

### ISSUE THREAD

**Issue by AJSturrock** [moltin/ruby-sdk#1]
Within the PHP SDK we have a method that generates the cart ID (which can be anything set by the user) which is then stored in a "mcart" cookie - https://github.com/moltin/php-sdk/blob/version1/src/Moltin/SDK/SDK.php#L131

This generated ID is then used automatically within the cart calls - https://github.com/moltin/php-sdk/blob/version1/src/Moltin/SDK/Facade/Cart.php

@marcqualie does the Ruby SDK handle cart identifiers and storage?

**Comment by marcqualie** [comment]
The SDK does handle all cart functions, but not storage. In ruby, each framework has their own storage mechanisms and there's no concept of a global session or cookie like PHP.

https://github.com/moltin/ruby-sdk/blob/master/lib/moltin/resource/cart.rb

Raw ruby:

``` ruby
cart = Cart.new # if no id is passed, a unique(ish) string will be generated
cart.add_item product_instance
cart.destroy
```

In Rails, sessions can be used during the request phase.

``` ruby
class ApplicationController < ActionController::Base
  def cart
    @cart ||= begin
      cart_id = session[:cart_id]
      Moltin::Resource::Cart.new cart_id if cart_id.present?
    end
  end
end
# Then accessed via "cart" helper anywhere in a controller
```

Another way I tested it in an example app was to link it to the logged in user. Each user has one cart, with it's own ID.

``` ruby
cart = Moltin::Resource::Cart.new current_user.moltin_cart_id
```

**Comment by AJSturrock** [comment]
Sounds good, thanks for the examples!
